com.fasterxml.jackson.*:* = 2.21.0
com.fasterxml.jackson.core:jackson-annotations = 2.21
com.squareup:javapoet = 1.13.0
com.palantir.javapoet:javapoet = 0.11.0
com.palantir.javaformat:* = 2.88.0
com.google.guava:guava = 33.5.0-jre
org.junit.jupiter:* = 6.0.3
org.assertj:assertj-core = 3.27.7
org.junit.platform:* = 6.0.3
org.mockito:* = 5.21.0
